name: Validate Docker Compose (Frontend)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Docker Compose syntax
        run: |
          docker --version
          docker compose version
          docker compose -f docker-compose.yml config
